version: "3.9"

services:

  mysql:
    image: "mysql:latest"
    container_name: "mysql_db"
    restart: always
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=identity
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks: [ "microservices" ]

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    container_name: "phpmyadmin"
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    networks: [ "microservices" ]

volumes:
  mysql_data: {}

networks:
  microservices:
    name: microservices
